name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }} with stylelint ${{ matrix.dep-versions.stylelint }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
          - 14
          - 12
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        dep-versions:
          - stylelint: 14
            recommended: 5
          - stylelint: 13
            recommended: 4
          - stylelint: 12
            recommended: 4
          - stylelint: 11
            recommended: 4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - env:
          STYLELINT_VERSION: ${{ matrix.dep-versions.stylelint }}
          RECOMMENDED_VERSION: ${{ matrix.dep-versions.recommended }}
        run: npm install --no-save "stylelint@${STYLELINT_VERSION}" "stylelint-config-recommended-scss@${RECOMMENDED_VERSION}"
      - run: npm test
